# Main configuration
mainConfiguration:
  platforms:
    - Steam
  notificationChannel: Ntfy # Supported channels: Ntfy, Email

settings:
  # Notifications specific settings
  channelSettings:
    Ntfy:
      topic: free-games # Your Ntfy topic name
      token: secretToken # Your Ntfy app token

  # Platform specific settings
  platformSettings:
    Steam:
      # List types of games (supported types: games, software, dlcs, demos, soundtracks,
      # playtests, videos, mods, hardware, bundles)
      types: [games, dlcs]
