# Main configuration
mainConfiguration:
  platforms:
    - Mocked
  notificationChannels: # Supported channels: Ntfy, Discord
    - Ntfy
    - Discord
# Configuration settings
settings:
  # Notifications specific settings
  channelSettings:
    Ntfy:
      topic: free-games # Your Ntfy topic name
      token: secretToken # (optional) Your Ntfy app token
    Discord:
      webhookUrl:

  # Platform specific settings
  platformSettings:
    Steam:
      # List types of games (supported types: games, software, dlcs, demos, soundtracks,
      # playtests, videos, mods, hardware, bundles)
      types: [games, dlcs]
    Mocked:
      amountOfGames: 1
