# Main configuration
mainConfiguration:
  platforms:
  - Mocked
  #- Steam
  #- EpicGames #not supported
  #- GOG # not supported
  notificationChannels:
  - Ntfy

# Configuration settings
settings:
  # Notifications specific settings
  channelSettings:
    Ntfy:
      topic: free-games
      url: https://ntfy.sh
      # Optional token for authentication
      #token: ''
      # must be base64 encoded
      #echo -n "Basic `echo -n 'testuser:fakepassword' | base64`" | base64 | tr -d '='
      # use above in shell to generate token
    Discord:
      webhookUrl: https://discord.com/api/webhooks/...

  # Platform specific settings
  platformSettings:
    Steam:
      types: [ games, dlcs ]
      schedule:
        interval: 30
    EpicGames:
      schedule:
        interval: 30
    GOG:
      #types: [ games, dlcs ] 
      schedule:
        interval: 30
    Mocked:
      amountOfGames: 1
      schedule:
        interval: 10
