# Main configuration
mainConfiguration:
  platforms:
    - Mocked
  notificationChannels:
    - Ntfy

# Configuration settings
settings:
  # Notifications specific settings
  channelSettings:
    Ntfy:
      topic: free-games
    Discord:
      webhookUrl: https://discord.com/api/webhooks/...

  # Platform specific settings
  platformSettings:
    Steam:
      types: [games, dlcs]
      schedule:
        interval: 30
    Mocked:
      amountOfGames: 1
      schedule:
        interval: 10
